services:
  mongo:
    image: mongo:4.4.6-bionic
    command: mongod --bind_ip 0.0.0.0
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=squirrel"
      - "MONGO_INITDB_ROOT_PASSWORD=${SQUIRREL_MONGO_PASSWORD}"
    ports:
      - 41090:27017
    volumes:
      - type: volume
        source: mongo
        target: /data/db

volumes:
  mongo:
